apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
  annotations:
    networking.istio.io/service-type: ClusterIP
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx
spec:
  parentRefs:
  - name: nginx-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /nginx
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: nginx
      port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute 
metadata:
  name: nginx-httproute
spec:
  parentRefs:
  - group: ""
    name: nginx
    port: 80
    kind: service
  rules:
  - backendRefs:
    - name: nginx-v1
      port: 80
    - name: nginx-v2
      port: 80
    match:
    - path:
      type: PathPrefix
      value: /nginx
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /